/* SAY PROMPTER - components/imageAttach.js
 * 참고 이미지는 크기 측정용이 아니라 디자인·배치·스타일 참고용이다.
 */
(function (global) {
  'use strict';
  var ROLES=['디자인 느낌','화면 배치','기능·사용 흐름','현재 화면','원하는 화면','기타'];
  var seq=0;
  function readFiles(fileList,cb){var files=Array.prototype.slice.call(fileList||[]).filter(function(f){return /^image\/(jpeg|png|webp)/i.test(f.type||'');});if(!files.length){cb([]);return;}var out=new Array(files.length),done=0;function finish(){if(++done===files.length)cb(out.filter(Boolean));}files.forEach(function(file,i){var r=new FileReader();r.onload=function(){out[i]={id:'img'+Date.now()+'_'+(++seq),name:file.name||('참고 이미지 '+(i+1)),dataUrl:r.result,role:'디자인 느낌',description:''};finish();};r.onerror=finish;r.readAsDataURL(file);});}
  function render(gridEl,countEl,images,handlers){gridEl.innerHTML='';countEl.textContent=images.length?('사진 '+images.length+'장'):'';images.forEach(function(img,i){var box=document.createElement('div');box.className='thumb';if(img.dataUrl){var pic=document.createElement('img');pic.src=img.dataUrl;pic.alt='참고 이미지 '+(i+1);box.appendChild(pic);}var body=document.createElement('div');body.className='thumb-body';var name=document.createElement('div');name.className='thumb-name';name.textContent='참고 이미지 '+(i+1);body.appendChild(name);var sel=document.createElement('select');sel.className='thumb-role';sel.setAttribute('aria-label','참고할 부분');ROLES.forEach(function(r){var o=document.createElement('option');o.value=r;o.textContent=r;o.selected=r===img.role;sel.appendChild(o);});sel.addEventListener('change',function(){handlers.onRole(img.id,sel.value);});body.appendChild(sel);var memo=document.createElement('input');memo.type='text';memo.className='thumb-memo';memo.placeholder='이 이미지에서 참고할 점 (예: 색은 빼고 좌우 배치만)';memo.value=img.description||'';memo.addEventListener('input',function(){handlers.onDescription(img.id,memo.value);});body.appendChild(memo);var guide=document.createElement('div');guide.className='thumb-guide';guide.textContent='똑같이 복제하는 용도가 아니라, 선호하는 디자인·배치·스타일을 프롬프트에 반영하기 위한 참고자료입니다.';body.appendChild(guide);var del=document.createElement('button');del.type='button';del.className='thumb-del';del.textContent='삭제';del.addEventListener('click',function(){handlers.onDelete(img.id);});body.appendChild(del);box.appendChild(body);gridEl.appendChild(box);});}
  global.SP=global.SP||{};global.SP.imageAttach={readFiles:readFiles,render:render,ROLES:ROLES};
})(window);
