/* SAY PROMPTER - components/linkAttach.js
 * 참고 링크는 구조·사용 흐름·기능 배치 참고용이다.
 * 브라우저 제한(CORS 등)으로 읽지 못할 수 있으며, 실패를 성공처럼 표시하지 않는다.
 */
(function (global) {
  'use strict';
  var seq=0;
  function normalizeUrl(raw){var u=String(raw||'').trim();if(!u)return'';if(!/^https?:\/\//i.test(u))u=(/^(localhost|127\.0\.0\.1)(:|\/|$)/i.test(u)?'http://':'https://')+u;try{var parsed=new URL(u),host=parsed.hostname;if(!host)return'';var ok=host.indexOf('.')!==-1||host==='localhost'||/^\d{1,3}(\.\d{1,3}){3}$/.test(host);return ok?parsed.href:'';}catch(e){return'';}}
  function create(url){return{id:'lnk'+Date.now()+'_'+(++seq),url:url,status:'idle',title:'',description:'',text:'',note:''};}
  function fetchContent(link){link.status='loading';return fetch(link.url,{mode:'cors',credentials:'omit'}).then(function(res){if(!res.ok)throw new Error('HTTP '+res.status);return res.text();}).then(function(html){var doc=new DOMParser().parseFromString(html,'text/html');link.title=((doc.querySelector('meta[property="og:title"]')||{}).content||doc.title||'').trim();link.description=((doc.querySelector('meta[property="og:description"]')||{}).content||(doc.querySelector('meta[name="description"]')||{}).content||'').trim();var main=doc.querySelector('main')||doc.querySelector('article')||doc.body;link.text=main?String(main.textContent||'').replace(/\s+/g,' ').trim().slice(0,500):'';if(!link.title&&!link.description&&!link.text)throw new Error('읽을 수 있는 내용이 없습니다');link.status='ok';return link;}).catch(function(){link.status='failed';return link;});}
  function render(listEl,links,handlers){listEl.innerHTML='';links.forEach(function(l,i){var row=document.createElement('div');row.className='link-item';var head=document.createElement('div');head.className='link-head';var idx=document.createElement('span');idx.className='link-idx';idx.textContent='참고 링크 '+(i+1);head.appendChild(idx);var a=document.createElement('a');a.className='link-url';a.href=l.url;a.target='_blank';a.rel='noreferrer noopener';a.textContent=l.url;head.appendChild(a);var badge=document.createElement('span');badge.className='link-badge';badge.textContent=l.status==='ok'?'기본 정보 확인됨':l.status==='loading'?'확인 중…':l.status==='failed'?'주소만 참고':'주소 참고';head.appendChild(badge);var del=document.createElement('button');del.type='button';del.className='link-del';del.textContent='삭제';del.addEventListener('click',function(){handlers.onDelete(l.id);});head.appendChild(del);row.appendChild(head);if(l.status==='ok'&&(l.title||l.description)){var got=document.createElement('div');got.className='link-got';got.textContent=[l.title,l.description].filter(Boolean).join(' — ').slice(0,180);row.appendChild(got);}var memo=document.createElement('input');memo.type='text';memo.className='link-memo';memo.placeholder='이 사이트에서 참고할 점 (예: 상품 등록 → 미리보기 → 공개 흐름)';memo.value=l.note||'';memo.addEventListener('input',function(){handlers.onNote(l.id,memo.value);});row.appendChild(memo);listEl.appendChild(row);});}
  global.SP=global.SP||{};global.SP.linkAttach={normalizeUrl:normalizeUrl,create:create,fetchContent:fetchContent,render:render};
})(window);
